### ISSUE TITLE
Support for listening on multiple sockets

### ISSUE THREAD

**Issue by mmatuska** [jabberd2/jabberd2#104]
Jabberd is missing the support for listening on multiple sockets (e.g. c2s, s2s). This would allow to bind on mixed multiple IPv4 and IPv6 addresses. The IP address for outgoing connections (currently called local IP) could be specified individually as well.

**Comment by smokku** [comment]
jabberd2 suports listening on multiple addresses by running multiple copies of c2s and/or s2s.
