### ISSUE TITLE
jabberd-2.3.4 [C2S] authreg_pgsql.so: undefined symbol: _BF_body_r

### ISSUE THREAD

**Issue by ungifted** [jabberd2/jabberd2#105]
Sat Oct 31 12:09:38 2015 [info] loading 'pgsql' authreg module
Sat Oct 31 12:09:38 2015 [error] failed loading authreg module 'pgsql' (/usr/lib/jabberd/authreg_pgsql.so: undefined symbol: _BF_body_r)
Segmentation fault

**Comment by smokku** [comment]
Very strange.
I am using PostgreSQL backend on my machines and it works fine.

Which version of PostgreSQL is it? Is it your own build? Some packaged one?

**Comment by ungifted** [comment]
[ebuild   R    ] dev-db/postgresql-9.4.5-r1:9.4::gentoo  USE="pam readline server zlib -doc -kerberos -ldap (-libressl) -nls -perl -pg_legacytimestamp -python (-selinux) -ssl -static-libs -tcl -threads -uuid -xml" LINGUAS="en ru -af -cs -de -es -fa -fr -hr -hu -it -ko -nb -pl -pt_BR -ro -sk -sl -sv -tr -zh_CN -zh_TW" PYTHON_SINGLE_TARGET="python3_4 -python2_7" PYTHON_TARGETS="python3_4 -python2_7" 0 KiB

but ebuild for jd2 copy-pasted from my own (removed unused use-flags/options) 2.3.3 ebuild.
[ebuild   R    ] net-im/jabberd2-2.3.4::x-portage  USE="debug postgres ssl zlib (-libressl) {-test}" 0 KiB

        econf \
                --sysconfdir=/etc/jabber \
                $(usex debug "--enable-debug" "") \
                $(use_enable ssl) \
                $(use_enable postgres pgsql) \
                --enable-pipe \
                --enable-anon \
                --enable-fs \
                $(use_enable test tests) \
                $(use_with zlib)

**Comment by smokku** [comment]
Very similar setup here.
Are you sure jabberd2 was built against the same postgres client libs that it is run on?

**Comment by ungifted** [comment]
Heh.... spent a lot of time on postgresql, but issue was in jabberd2.
It seems util/crypt_blowfish.c for i386 need http://cvsweb.openwall.com/cgi/cvsweb.cgi/Owl/packages/glibc/crypt_blowfish/x86.S and you miss it.

$ fgrep -A2 _i386_ util/crypt_blowfish.c 
#ifdef __i386__
#define BF_ASM			1
#define BF_SCALE			1

**Comment by ungifted** [comment]
BF_ASM 0 fixes c2s for me

**Comment by smokku** [comment]
So, if I get it right, your glibc is missing ASM implementation of Blowfish?

**Comment by ungifted** [comment]
It seems bcrypt not part of glibc and gentoo didn't add it into ebuild.
So, yes I havn't blowfish in glibc.

**Comment by smokku** [comment]
Any idea is there a way to detect it configure-time or build-time?

**Comment by ungifted** [comment]
You developer. I'm just stupid sysadmin :)

**Comment by smokku** [comment]
Well... _Your_ problem does not reproduce here.
Thus I need your cooperation in fixing it.

**Comment by sdebnath** [comment]
Couldn't we try searching for BF_body_r in the lib using AC_SEARCH_LIBS macro? An example where I look for uuid_create:

    AC_SEARCH_LIBS([uuid_create], [uuid ossp-uuid], [], [
        AC_MSG_ERROR([Unable to find uuid_create function])
    ])

**Comment by smokku** [comment]
Yeah. Could work. :)

**Comment by sdebnath** [comment]
Problem is the way jabberd2 is compiled, which is still a bit of a mystery to me, the issue is that compile worked but got runtime segfault. I had good luck with AC_SEARCH_LIBS.

**Comment by crosser** [comment]
I would maybe use AC_TRY_COMPILE instead, using BF_body() as canary, because nobody knows how future implementations of blowfish may change the chain of #defines. AC_SEARCH_LIBS may give you false negatives, I believe.
