### ISSUE TITLE
jabberd-2.3.6 bad auth request / presence

### ISSUE THREAD

**Issue by ungifted** [jabberd2/jabberd2#113]
I believe you rename issue later. I don't know real issue nature. Sorry

New user (new@example.com) have roster from template/roster.xml with subscription='none'.
After logon I can ask subscription for any online user in roster (from new@example.com/RESNEW to old@example.com/RES).

After request I have: old@example.com in right group and another new item old@example.com/RES without group. Both online. After relogon both offline.
In "roster-items" I have  "collection-owner"=old@example.com  jid='new@example.com/RESNEW'

Here is xml from psi+ for 1 auth request:
[psi1.txt](https://github.com/jabberd2/jabberd2/files/169198/psi1.txt)

**Comment by smokku** [comment]
Presence subscription is Bare-JID based.
You should send subscription request to Bare-JID (without resource) of your contact, not to Full-JID. https://tools.ietf.org/html/rfc6121#section-3.1.1

Server does not process directed presence packets (presence packets to a Full-JID) as per https://tools.ietf.org/html/rfc6121#section-4.4.3 - these get delivered directly to all new@example.com connected clients and do not cause presence subscription change on server side.

**Comment by ungifted** [comment]
Ok, It may be client side issue with psi+. ATM I have to build jd2 with dropped https://github.com/jabberd2/jabberd2/commit/cdf4d372f28fc875a673ed09465bd4939400edd2

But does it right Full-JIDs in roster-items table?

**Comment by smokku** [comment]
FullJID roster items are a controversial yet fully valid use case. https://www.ietf.org/mail-archive/web/xmpp/current/msg02557.html

**Comment by smokku** [comment]
What is your exact issue with cdf4d37? 
You should not attempt to establish presence relationship for FullJID roster items. Add another, BareJID item and establish presence relationship there.

**Comment by ungifted** [comment]
Fixed by bug 116š
