### ISSUE TITLE
"README.protocol" contains incorrect XEP description

### ISSUE THREAD

**Issue by Ploy-XIV** [jabberd2/jabberd2#114]
The protocol overview contains the following line:

    XEP-0198 Stanza Acknowledgements

XEP-0198 is called "Stream Management" (see: http://xmpp.org/extensions/xep-0198.html). There is no XEP called "Stanza Acknowledgements".

Please update the documentation accordingly.

**Comment by smokku** [comment]
Compare _Appendix H: Revision History_ http://xmpp.org/extensions/xep-0198.html#appendix-revs

> **Version 0.4 (2008-09-08)**
> Added support for session resumption; re-organized the document; **changed name to stream management**; changed provisional namespace.
> (jjh/jk/psa)

jabberd2 implements an older revision of XEP-0198, when it was still called "Stanza Acknowledgements"
