### ISSUE TITLE
mu-conference considering user is offline

### ISSUE THREAD

**Issue by niki-eng** [jabberd2/jabberd2#115]
Hello,

I use jabberd2 and MU-conference for small office chat communication. There are situations when users loose connectivity and get back online in 1-2 minutes but with different IP address received from the internet service provider. In these cases they cannot join to mu-conference group chat, receiving an error "Conflict" in pidgin client. In MU-conference log there's a message like this:
MU-Conference: [conference.c:595 (_con_packets)] Nick Conflict 

5-10 minutes later users can join again the group chat, so I suppose there's some timeout after that user from the group chat is considered offline and is able to join again. 

I was thinking for XEP-0199 - XMPP Ping from server to client but I don't know how to use it with MU-conference and if it would be useful at all.

Is there any way to deal with this problem?

**Comment by smokku** [comment]
There is some issue with jabberd2 detecting that your connection dropped and closing your session then - thus logging out of MUC.
Try tuning your TCP keepalives on OS kernel level, or enable stream level keepalives in jabberd2 c2s configuration: https://github.com/jabberd2/jabberd2/blob/master/etc/c2s.xml.dist.in#L335 - a comment there explains how it works.

**Comment by niki-eng** [comment]
Smokku, thank you for support. Actually your advice solved the problem, so I owe you.

Best Regards!
