### ISSUE TITLE
Websockets

### ISSUE THREAD

**Issue by sajax88** [jabberd2/jabberd2#117]
There's practically no information on new websocket plugin included in latest versions. Please help me to enable it. I uncommented it in c2s.xml, but what port should I send my requests from browser to? Now if i send them to 5222, I get Error during WebSocket handshake: Invalid status line answer and these lines in log:

Thu Apr 28 18:42:22 2016 [notice] [10] [95.220.117.49, port=53429] connect
Thu Apr 28 18:42:22 2016 [notice] [10] [95.220.117.49, port=53429] error: XML parse error (syntax error)
Thu Apr 28 18:42:22 2016 [notice] [10] [95.220.117.49, port=53429] disconnect jid=unbound, packets: 0, bytes: 0

Need help desperately)

**Comment by smokku** [comment]
There's not much to document. You enable Websocket support in c2s.xml and connect 5222 (or 5223 for wss:// ).
I tested it with Strophe only, so there still may be some bugs there.
- What client are you using?
- Which version of jabberd?
- See debug log of c2s (c2s -D) and post it here.
- Could you dump client-side of conversation and post it here?

**Comment by sajax88** [comment]
Thank you for answering! I'm also using strophe, and jabberd2.3.6.
Unfortunately, there's almost nothing in debug log, only lines about sqlite start:

Thu Apr 28 18:54:19 2016 [info] loading 'sqlite' authreg module
Thu Apr 28 18:54:19 2016 [notice] initialized auth module 'sqlite'

And Strophe only says it's disconnected and puts this line in console:
strophe.js:5272 WebSocket connection to 'ws://xmpp.getlessons.1gb.ru:5222/' failed: Error during WebSocket handshake: Invalid status line

The problem seems to be that server sends 200 status code instead of 101. But I don't know why it does it)

**Comment by smokku** [comment]
You need to have jabberd compiled `--with-debug` and run c2s with `-D` switch to get debug log.

Please open debugging console in browser and in Network tab you should see your ws:// connection - there you will be able to see the frames exchange.

**Comment by smokku** [comment]
You may also try connecting your client to my home server: `ws://chrome.pl:5223/ws` to check your client. (Just use some bogus authorization info, to just check the message exchange.)

**Comment by smokku** [comment]
You may also want to open http://xmpp.getlessons.1gb.ru:5222/ in browser and see what happens.

**Comment by smokku** [comment]
From what I see it behaves like you did not enable Websocket.
Did you compile jabberd `--with-websocket` option?

**Comment by sajax88** [comment]
>> You need to have jabberd compiled --with-debug and run c2s with -D switch to get debug log.

I compiled it with --enable-debug option and --enable-websocket (there're no --with- options, so I think that's it). And jabberd2 runs as service (I have CentOS), so I uncommented debug log path in config - is that enough to enable debugging?

If I just open it in browser, I get the same response:

<stream:stream xmlns:stream='http://etherx.jabber.org/streams' version='1.0'><stream:error xmlns:stream='http://etherx.jabber.org/streams'><xml-not-well-formed xmlns='urn:ietf:params:xml:ns:xmpp-streams'/><text xmlns='urn:ietf:params:xml:ns:xmpp-streams'>syntax error</text></stream:error></stream:stream>

In Chrome Network tab I see response headers:

Request URL:ws://xmpp.getlessons.1gb.ru:5222/
Request Method:GET
Status Code:200 OK

And that is all)

**Comment by smokku** [comment]
`--with-` and `--enable-` options are the same :)
You need to actually run c2s process with `-D` switch to enable debug logging in process. It is best to start it manually on the console for the time of debugging.

Still, your jabberd behaves like you do not have websocket support compiled-in. Are you sure it detected your `http_parser` library correctly during ./configure?

**Comment by sajax88** [comment]
OMG, I'm so sorry I've been bothering you. I've just recompiled it and it's working now! Let's pretend this conversation never happened )) Thank you so much for your patience)

**Comment by smokku** [comment]
Well... I need to fix one thing then - you should get an error message in log, that you tried enabling websocket, which you don't have support for. :)

**Comment by sajax88** [comment]
Good to know all this has not been in vain :)

**Comment by sajax88** [comment]
Please excuse me once more: there's the same error with port 5223 now (5222 works fine).

Fri Apr 29 13:43:06 2016 [notice] [10] [95.220.117.49, port=56674] connect
Fri Apr 29 13:43:06 2016 [notice] [10] [95.220.117.49, port=56674] error: XML parse error (syntax error)
Fri Apr 29 13:43:06 2016 [notice] [10] [95.220.117.49, port=56674] disconnect jid=unbound, packets: 0, bytes: 0

And here's debug log:

Fri Apr 29 13:43:52 2016 c2s.c:563 accept action on fd 10
Fri Apr 29 13:43:52 2016 [notice] [10] [95.220.117.49, port=56717] connect
Fri Apr 29 13:43:52 2016 c2s.c:37 want read
Fri Apr 29 13:43:52 2016 c2s.c:515 read action on fd 10
Fri Apr 29 13:43:52 2016 c2s.c:47 reading from 10
Fri Apr 29 13:43:52 2016 c2s.c:106 read 517 bytes
Fri Apr 29 13:43:52 2016 c2s.c:42 want write
Fri Apr 29 13:43:52 2016 c2s.c:529 write action on fd 10
Fri Apr 29 13:43:52 2016 c2s.c:113 writing to 10
Fri Apr 29 13:43:52 2016 c2s.c:117 137 bytes written
Fri Apr 29 13:43:52 2016 c2s.c:37 want read
Fri Apr 29 13:43:52 2016 c2s.c:515 read action on fd 10
Fri Apr 29 13:43:52 2016 c2s.c:47 reading from 10
Fri Apr 29 13:43:52 2016 c2s.c:106 read 51 bytes
Fri Apr 29 13:43:52 2016 c2s.c:515 read action on fd 10
Fri Apr 29 13:43:52 2016 c2s.c:534 close action on fd 10
Fri Apr 29 13:43:52 2016 [notice] [10] [95.220.117.49, port=56717] disconnect jid=unbound, packets: 0, bytes: 0
Fri Apr 29 13:43:52 2016 websocket.c:573 cleaning up websocket state
Fri Apr 29 13:43:52 2016 ssl.c:855 cleaning up conn state
Fri Apr 29 13:43:52 2016 c2s.c:563 accept action on fd 10
Fri Apr 29 13:43:52 2016 [notice] [10] [95.220.117.49, port=56718] connect
Fri Apr 29 13:43:52 2016 c2s.c:37 want read
Fri Apr 29 13:43:52 2016 c2s.c:515 read action on fd 10
Fri Apr 29 13:43:52 2016 c2s.c:47 reading from 10
Fri Apr 29 13:43:52 2016 c2s.c:106 read 517 bytes
Fri Apr 29 13:43:52 2016 c2s.c:42 want write
Fri Apr 29 13:43:52 2016 c2s.c:529 write action on fd 10
Fri Apr 29 13:43:52 2016 c2s.c:113 writing to 10
Fri Apr 29 13:43:52 2016 c2s.c:117 137 bytes written
Fri Apr 29 13:43:52 2016 c2s.c:37 want read
Fri Apr 29 13:43:52 2016 c2s.c:515 read action on fd 10
Fri Apr 29 13:43:52 2016 c2s.c:47 reading from 10
Fri Apr 29 13:43:52 2016 c2s.c:106 read 51 bytes
Fri Apr 29 13:43:52 2016 c2s.c:515 read action on fd 10
Fri Apr 29 13:43:52 2016 c2s.c:47 reading from 10
Fri Apr 29 13:43:52 2016 c2s.c:106 read 596 bytes
Fri Apr 29 13:43:52 2016 [notice] [10] [95.220.117.49, port=56718] error: XML parse error (syntax error)
Fri Apr 29 13:43:52 2016 c2s.c:42 want write
Fri Apr 29 13:43:52 2016 c2s.c:529 write action on fd 10
Fri Apr 29 13:43:52 2016 c2s.c:113 writing to 10
Fri Apr 29 13:43:52 2016 c2s.c:117 106 bytes written
Fri Apr 29 13:43:52 2016 c2s.c:37 want read
Fri Apr 29 13:43:52 2016 c2s.c:529 write action on fd 10
Fri Apr 29 13:43:52 2016 c2s.c:113 writing to 10
Fri Apr 29 13:43:52 2016 c2s.c:117 241 bytes written
Fri Apr 29 13:43:52 2016 c2s.c:37 want read
Fri Apr 29 13:43:52 2016 c2s.c:529 write action on fd 10
Fri Apr 29 13:43:52 2016 c2s.c:113 writing to 10
Fri Apr 29 13:43:52 2016 c2s.c:117 45 bytes written
Fri Apr 29 13:43:52 2016 c2s.c:534 close action on fd 10
Fri Apr 29 13:43:52 2016 [notice] [10] [95.220.117.49, port=56718] disconnect jid=unbound, packets: 0, bytes: 0
Fri Apr 29 13:43:52 2016 websocket.c:573 cleaning up websocket state
Fri Apr 29 13:43:52 2016 ssl.c:855 cleaning up conn state

**Comment by smokku** [comment]
wss:// is broken in 2.3.6. You need current :master code for this to work.
