### ISSUE TITLE
c2s failed to load  SSL pemfile on RHEL 6.8

### ISSUE THREAD

**Issue by psegedy** [jabberd2/jabberd2#124]
Hi,
when I run c2s -D on RHEL 6.8 I get
```
sx (ssl.c:910) initialising ssl plugin
sx (ssl.c:993) Restricting TLS ciphers to PROFILE=SYSTEM
sx (ssl.c:995) Can't set cipher list for SSL context: error:1410D0B9:SSL routines:SSL_CTX_set_cipher_list:no cipher match
Wed Sep 14 11:40:10 2016 [error] failed to load  SSL pemfile
```
so PROFILE=SYSTEM is wrong value of ciphers variable from int sx_ssl_init(sx_env_t env, sx_plugin_t p, va_list args) in /sx/ssl.c

when I run it on RHEL 7 with same c2s.xml configuration
```
sx (ssl.c:910) initialising ssl plugin
sx (ssl.c:993) Restricting TLS ciphers to !aNULL:!eNULL:!EXP:ALL:!aNULL:!eNULL:!SSLv2:!EXPORT:!RC2:!DES
sx (ssl.c:1022) No CA chain specified. Loading SSL default CA certs: /etc/ssl/certs
sx (ssl.c:1058) setting ssl context '' verify mode to 00
sx (ssl.c:993) Restricting TLS ciphers to !aNULL:!eNULL:!EXP:ALL:!aNULL:!eNULL:!SSLv2:!EXPORT:!RC2:!DES
sx (ssl.c:1022) No CA chain specified. Loading SSL default CA certs: /etc/ssl/certs
sx (ssl.c:1058) setting ssl context '*' verify mode to 00
sx (ssl.c:1105) ssl context '*' initialised; certificate and key loaded from /etc/pki/spacewalk/jabberd/server.pem
sx (ssl.c:1105) ssl context '' initialised; certificate and key loaded from /etc/pki/spacewalk/jabberd/server.pem
```

Any idea what could be wrong on RHEL 6 ?
Thanks

**Comment by smokku** [comment]
What is the value of `ciphers` in your `c2s.xml` on RHEL 6?

**Comment by psegedy** [comment]
It isn't set in `c2s.xml`. Even when I set it to `<ciphers>!aNULL:!eNULL:!EXP:ALL:!aNULL:!eNULL:!SSLv2:!EXPORT:!RC2:!DES</ciphers>
` it result in same result
```
sx (ssl.c:993) Restricting TLS ciphers to PROFILE=SYSTEM
```

**Comment by smokku** [comment]
What version of jabberd are you running on RHEL 6?

**Comment by smokku** [comment]
I was sure I've already seen it somewhere... Here! https://bugzilla.redhat.com/show_bug.cgi?id=1179229

Looks like your packager patched it in.

**Comment by mcepl** [comment]
@psegedy could you try to test with http://koji.fedoraproject.org/koji/taskinfo?taskID=15641361, please?

**Comment by psegedy** [comment]
@mcepl  I tested it and it works now :+1:
