### ISSUE TITLE
CRYPTO_lock removed from OpenSSL 1.1.0

### ISSUE THREAD

**Issue by jas4711** [jabberd2/jabberd2#125]
Apparently CRYPTO_lock has been removed from OpenSSL 1.1.0.  The configure.ac file uses it, but I don't see it used in code.  Is there some other symbol that could be used as a OpenSSL-version check instead?  Thanks.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828360

**Comment by adrianreber** [comment]
Same error in the development branch of Fedora:

http://koji.fedoraproject.org/koji/taskinfo?taskID=16046027
