### ISSUE TITLE
c2s ciphers get ignored?

### ISSUE THREAD

**Issue by hasufell** [jabberd2/jabberd2#127]
I'm running a jabberd2 server with a restricted set of ciphers:
```
# grep ciphers /etc/jabber/*.xml
/etc/jabber/c2s.xml:    <ciphers>ECDHE-RSA-AES256-GCM-SHA384 ECDHE-RSA-AES256-SHA384 ECDHE-RSA-AES256-SHA DHE-RSA-AES256-GCM-SHA384 DHE-RSA-CAMELLIA256-SHA DHE-RSA-AES256-SHA256 DHE-RSA-AES256-SHA</ciphers>
/etc/jabber/s2s.xml:    <ciphers>ECDHE-RSA-AES256-GCM-SHA384 ECDHE-RSA-AES256-SHA384 ECDHE-RSA-AES256-SHA DHE-RSA-AES256-GCM-SHA384 DHE-RSA-CAMELLIA256-SHA DHE-RSA-AES256-SHA256 DHE-RSA-AES256-SHA</ciphers>
```

Both are under `<local>... </local>`. For the s2s module, IM Observatory [reports](https://xmpp.net/result.php?id=527276#ciphers) the ciphers correctly. But for c2s [the results](https://xmpp.net/result.php?id=527518#ciphers) indicate that it's still using the default list of ciphers.

jabberd2 version is 2.4.0.

**Comment by smokku** [comment]
`c2s/local/ciphers` setting is for `xmpps` port (5223). You need to set `ciphers` (as well as `pemfile`) in `c2s/local/id` of each vhost.

I guess it is undocumented in comments. Will fix it then.

**Comment by smokku** [comment]
Turns out it is documented: https://github.com/jabberd2/jabberd2/blob/master/etc/c2s.xml.dist.in#L114

Closing then.
