### ISSUE TITLE
Service doesn't autostart in systemd

### ISSUE THREAD

**Issue by thany** [jabberd2/jabberd2#128]
Well, it does. At first, it didn't even wait for mysql to become available.

```
[error] mysql: connection to database failed: Can't connect to local MySQL server through socket
```

Now I've manually edited the `jabberd-sm.service` to include `mysql.service` in `After=` *and* `Requires=`. Those log entries seem to be gone. Can't be too sure though, systemd is a total maze to me. And the fact that it silently ignores any misconfiguration is a real big help, too.

So now, it's trying to start, and connects to mysql, and shuts itself down. And that's the end of that. It doesn't even think to try again in a minute or so.

Here's a bit of log:
```
Sat Oct 15 00:37:49 2016 [notice] starting up
Sat Oct 15 00:37:49 2016 [error] couldn't open /var/run/jabberd2/sm.pid for writing: No such file or directory
Sat Oct 15 00:37:49 2016 [info] loading 'mysql' storage module
Sat Oct 15 00:37:49 2016 [notice] initialised storage driver 'mysql'
Sat Oct 15 00:37:49 2016 [notice] modules search path: /usr/lib/x86_64-linux-gnu/jabberd2
Sat Oct 15 00:37:49 2016 [notice] module 'status' added to chain 'sess-start' (order 0 index 0 seq 0)
[ snip ]
Sat Oct 15 00:37:49 2016 [notice] module 'iq-version' added to chain 'disco-extend' (order 0 index 17 seq 1)
Sat Oct 15 00:37:49 2016 [notice] module 'help' added to chain 'disco-extend' (order 1 index 18 seq 1)
Sat Oct 15 00:37:49 2016 [notice] version: jabberd2 sm 2.3.4
Sat Oct 15 00:37:49 2016 [notice] [thany.nl] configured
Sat Oct 15 00:37:49 2016 [notice] attempting connection to router at 127.0.0.1, port=5347
Sat Oct 15 00:37:49 2016 [notice] connection to router established
Sat Oct 15 00:37:49 2016 [notice] thany.nl ready for sessions
Sat Oct 15 00:38:19 2016 [notice] shutting down
Sat Oct 15 00:38:19 2016 [notice] connection to router closed
```

It seems I *have to* start the service manually after every reboot. That seems the only way to get the service to start.

This is on Ubuntu 16.04 and Jabberd 2.3.4.

**Comment by smokku** [comment]
I don't believe this is a jabberd2 issue.

Please raise this on Ubuntu bug tracker or mailing list.

**Comment by thany** [comment]
How is this a problem in Ubuntu?

1) Shouldn't jabberd2 provide a working jabberd-*.service file for systemd? Mysql has explicit support for systemd in this way as well, so I cannot go and fault Ubuntu for not supporting jabberd2 properly, can I?

2) And I'm not even sure if a dependency on mysql like that will work, as mysql tends to reported "I'm started" before applications can actuallt connect to it. Or so I've heard. For this reason, jabberd2 should wait for mysql connections to become available.

I'm not sure which of the two applies exactly, but I'm fairly sure it has nothing to do with the OS.

**Comment by smokku** [comment]
1. jabberd2 provides exemple service file. It is up to deployment to customize for particular use case. It is impossible to create _one-size-fits-all_ solution working in all possible deployments. Please contact Ubuntu maintainer of jabberd2 package, to apply proper changes to the package. jabberd2 can't possibly support every deployment that could ever come into existence.

2. This will not work for deployments running different storage backend than MySQL. These would wait forever as MySQL will never be started.

**Comment by thany** [comment]
As for 2: if the storage backend is different than mysql, of course you don't wait for it. What I'm saying is: _wait for the storage backend to become available_.

In case of MySQL, you (probably) need to wait for it to start accepting connections, proof for that is in the log: it will exit because MySQL refuses to accept connections yet, but it will successfully start if I start it manually, which is later, which is when MySQL has fully started.

**Comment by crosser** [comment]
@thany , there usually is a way to delay start of a service (jabberd2) until the other service (mysql) is ready, but the way to do it depends on the init system (and thus on the distro), and which storage backend to wait for depends on how you've built jabberd2. So, it is up for the distro package maintainer to set it up properly.

And yes, Debian/Ubuntu package of jabberd2 is a mess.

**Comment by thany** [comment]
Maybe provide a not so messy package then?

Look, Ubuntu (or really, Debian-based distros) are greatly popular, so it makes sense to get it to work flawlessly there.

I understand it's tempting to brush it off to Ubuntu, but it's jabberd that isn't working properly in the end. So folks will go here to report it. That to me, makes total sense.

**Comment by smokku** [comment]
If anyone would volunteer to provide non-messy Debian packages, I would *gladly* accept these.
But my own resources are limited and I simply cannot spend time to install and learn yet another Linux distribution. Especially to the point of building better packages than own Debian maintainers. Sorry.

**Comment by DenisVS** [comment]
Same issue in FreeBSD.
Jabberd is not start until mysqld is working.

**Comment by thany** [comment]
Problems like this might also be solvable if jabberd would be provided as a docker image. I'm not sure if it is, currenty. But since a docker "just works", there shouldn't be any distro-specific problems.

Not a perfect solution of course, to those who don't/can't use docker.

**Comment by thany** [comment]
Did yo just do a cursory search, or would you vouch for the docker packages you found there? Neither look "official", which might be a concern.
