### ISSUE TITLE
sm crashes after getting a HUP

### ISSUE THREAD

**Issue by gdt** [jabberd2/jabberd2#135]
After sm receives a HUP (can happen on boot), and someone logs in, it crashes.  The basic issue is that a config_t is apparently overwritten with the string "status", trashing the pointer to the hash table.  Or something else that ends up like that.

```
#0  0x080635de in xhash_getx (h=0x74617473, key=0xbb7e334c "storage.path", len=12) at xhash.c:174
#1  0x0806364f in xhash_get (h=0x74617473, key=<optimized out>) at xhash.c:187
#2  0x0805c426 in config_get_one (c=0xbb102060, key=0xbb7e334c "storage.path", num=0) at config.c:280
#3  0xbb7e258b in storage_add_type (st=0xbb10b040, driver=0xbb119028 "sqlite", type=0xbb06cb6a "active") at storage.c:114
#4  0xbb7e2a44 in storage_get (st=0xbb10b040, type=0xbb06cb6a "active", owner=0xbb12fc80 "user@examplecom", filter=0x0, os=0xbf7fe258) at storage.c:239
#5  0xbb06ca23 in _active_user_load (mi=0xbb12f660, user=0xbb11b550) at mod_active.c:35
```

You can see that argument h to frames 0 and 1 is suspect (should be a
pointer).  In frame 2, config_get_one has a config_t c which does
contain that value in c->hash.  But then I realized that (char *) &c->h
(also "c") is "status".

```
(gdb) print c
$1 = (config_t) 0xbb102060
(gdb) print *c
$2 = {hash = 0x74617473, nad = 0xbb007375}
(gdb) x/s c
0xbb102060:      "status"
```

This is 2.4.0, sqlite storage, NetBSD 6, i386, gcc 4.5.

**Comment by smokku** [comment]
Seems like #41 duplicate.

**Comment by smokku** [comment]
Looks like a new release is long time overdue...

**Comment by gdt** [comment]
I wonder also if issues should be closed until there is a fix in a release.   I looked at the open issues and did not find this.  But maybe having point releases on stable branches every time there is a serious bug fix, or at least every few months, would avoid having to think about that.

**Comment by smokku** [comment]
Agreed. This is a never-ending discussion, as both approaches have advantages and disadvantages. I settled on the one requiring less maintenance.
There is a neat link on GitHub: https://github.com/jabberd2/jabberd2/compare/jabberd-2.4.0...master
![screenshot1](https://cloud.githubusercontent.com/assets/147687/21686324/409c278a-d365-11e6-883e-7373112e97a6.png)
But it's not easily discoverable and is not ideal.
