### ISSUE TITLE
s2s is unable to connect on IPv6 only servers

### ISSUE THREAD

**Issue by zem** [jabberd2/jabberd2#136]
I have some trouble establishing s2s IPv6 connection:

Sun Jan  8 23:44:11 2017 [notice] dns lookup for jabber.metalab.at returned 1 result (ttl 299)
Sun Jan  8 23:44:11 2017 [notice] [-1] [146.255.63.7, port=5269] [local: ::] mio_connect error: Address family not supported by protocol (97)
Sun Jan  8 23:44:11 2017 [notice] [-1] [146.255.63.7, port=5269] unable to connect host

s2s tries to connect to the IPv4 Address by default, but the Server does not have IPv4.

**Comment by smokku** [comment]
Which jabberd version?

**Comment by smokku** [comment]
BTW, from the quoted log it looks like your server is trying to establish IPv4 connection _from_ your local `::` IPv6 address.

**Comment by zem** [comment]
Jabberd2  2.4.0
Yes it looks like it is trying to establish an IPv4 connection, but no IPv6 connection at all.

**Comment by smokku** [comment]
Did you set your `<origins>` as in #96?

**Comment by zem** [comment]
As far as I can tell, yes, it looks like this: 

  <origins>
      <ip>::</ip>
    </origins>

**Comment by smokku** [comment]
And after failing the IPv4 attempt it does not retry with IPv6?

**Comment by zem** [comment]
I can see no connection attempt at all neither in the log nor in netstat. 

It should try to connect to  2a02:1b8:10:47::22 (AAAA record of jabber.metalab.at) after that IPv4 connection fail. 

If the jabber.metalab.at server tries to connect inbound, too, comes in via IPv4 what you can see by the NAT64 addresses:  

Sun Jan  8 23:55:56 2017 [notice] [8] [64:ff9b::92ff:3f07, port=57891] incoming stream online (id zhib75wdpa12x29dxi1llhoxr5h08mz74ijbogpd)
Sun Jan  8 23:55:56 2017 [notice] [8] [64:ff9b::92ff:3f07, port=57891] received dialback auth request for route 'conesphere.com/jabber.metalab.at'

but the dialback always results in trying  the IPv4 address.

**Comment by smokku** [comment]
Did you enable `lookup.resolve-ipv6` in `s2s.xml`?

**Comment by crosser** [comment]
May I suggest @zem to try to specify

```
<origins>
  <ip>0.0.0.0</ip>
  <ip>::</ip>
</origins>
```
and see if the behaviour changes. I observed somewhat similar trouble a while ago, and reported it, but I cannot find my ticket now. Perhaps it was discussed in the commit comment thread? @smokku, do you recall? Sorry I cannot find any pointers now. I do remember that mio_connect() retry logic did look wrong to me at the time.

**Comment by crosser** [comment]
Here it is: issue #96

**Comment by smokku** [comment]
@crosser He wants an IPv6-only server, so no `<ip>0.0.0.0</ip>`.

**Comment by crosser** [comment]
@smokku I know, but the point is, I recall that there was an error in retry logic in mio_connect, when retry did not happen in some situation in which it should happen. Maybe the same error happens here.

**Comment by smokku** [comment]
AFAIR that retry logic is what #96 fixes.

**Comment by crosser** [comment]
You are right, commit c2a599b fixed the problem that I reported.
I think maybe that in this case, the problem is earlier:

```
dns lookup for jabber.metalab.at returned 1 result
```
and that result was an IPv4 address. So the for loop at out.c:538 did not find a match, and the fallback piece out.c:549 tried to open a connection to IPv4 address from the local IPv6 interface, which failed.

I would check the DNS resolver code next...

**Comment by smokku** [comment]
First I asked whether `lookup.resolve-ipv6` is enabled. This may be the reason for _returned 1 result_

**Comment by crosser** [comment]
Right. I just now noticed that this option exists, and is off by default ;) Should it be, by the way? Should AAAA lookup be enabled automatically if the host is capable of IPv6? Or even enabled unconditionally?

**Comment by smokku** [comment]
There are more IPv4-only servers than IPv6-capable.

"automatically" is not jabberd2 style.

**Comment by gdt** [comment]
I don't follow the "automatically is not jabberd2 style".  The internet norm these days is that v6 is normal (even if it is not yet as common).   So it seems that s2s, like every other protocol, should do a lookup for AAAA and A, and either try v6, then v4, or else have some happy-eyeballs code.  Certainly it makes sense to have a disable option for trying v6 (as well as a disable option for v4).

**Comment by smokku** [comment]
So, there is exactly that option: `lookup.enable-ipv6`. It is up to the deployment administrator to decide whether one wants to resolve AAAA or not.

**Comment by gdt** [comment]
My point is that in 2017, IPv6 should default to on.

**Comment by smokku** [comment]
I believe it is rude to change defaults between releases. Sysadmins do not like surprises.

On the other hand jabberd3 has IPv6 as primary with IPv4 mapped in `::FFFF:xxx.xxx.xxx.xxx`.

**Comment by zem** [comment]
A classical PEBKAC  I completely overlooked that  lookup.resolve-ipv6 setting in s2s.xml  thanks for your support.

**Comment by smokku** [comment]
Glad to help. :)
