### ISSUE TITLE
HowTo generate a valid TLS certificate

### ISSUE THREAD

**Issue by karstengit** [jabberd2/jabberd2#137]
I described the problem already here:
http://serverfault.com/questions/826269/working-tls-certificate-for-jabberd2-server

There are others out there with the same problem:
https://lists.freebsd.org/pipermail/freebsd-ports/2012-March/074073.html

Hopefully there will be an answer, but the problem is still unsolved up to now ...

**Comment by karstengit** [comment]
The problem is that X509 certificates seems not to be accepted by many clients.
https://developer.pidgin.im/ticket/17148#ticket

**Comment by smokku** [comment]
This is a bugtracker, not a help forum. Please report actual jabberd software bugs here only.

Discussion should be on to jabberd2 mailing list.

**Comment by karstengit** [comment]
O.K. You say it's a feature - not a bug.

But jabber2d is unusable under the aspect of privacy, because no client can connect in a secure way!
The documentation is incomplete how to configure a usable self signed TLS certificate.

**Comment by smokku** [comment]
1. You said that, not me.

2. Self-signed certificates are just an illusion of security. That is why most clients refuse to accept it. The easiest way to get a proper cert for your server is https://letsencrypt.org

3. You're right - the documentation is in awful state. Outdated, sometimes lain wrong. The most up to date documentation are the comments in the config file.

**Comment by karstengit** [comment]
1. Thanks for the support of "features".

2.  Why it's an illusion? \
It's not so easy to make a man in the middle attack when a certificate is checked and accepted. \
But you are right - i will check the using of https://letsencrypt.org \
It should be possible to use in an intranet self signed certificates to encrypt the communication without using an external authority!

3. I followed the comments specially in the config files and i was not able to master the problem.
Currently it is working only with the following construct:

```
  <local>
         <pemfile>/etc/jabberd2/jabber.pem</pemfile>
         <verify-mode>7</verify-mode>
         <require-starttls>1</require-starttls>
         <ciphers>EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH</ciphers>
    <id register-enable='mu'>mydomain.de</id>
  </local>

```
This is accepted as configuration without any error.
For me it is a bug that communication without encryption is allowed by the jabber server here!

**Comment by karstengit** [comment]
Please explain howto use the configuration option "cachain='/etc/jabberd2/client_ca_certs.pem'".

This would be helpful to test other variants of certificates.

**Comment by karstengit** [comment]
I am trying to generate some certificates including a client certificate following this description:
https://gist.github.com/mtigas/952344

The jabber server crashes at start!
Maybe RSA 4096 Bit is to secure for him - trying now 1024 ...

**Comment by karstengit** [comment]
It's the same trying it with RSA 1024 Bit key.
jabberd2-c2s and jabberd2-router are coring immediately after starting.

If you want to test it here are the generated keys:
[Jabber.zip](https://github.com/jabberd2/jabberd2/files/706699/Jabber.zip)
The passphrase is always jabber.

**Comment by karstengit** [comment]
Let's try to generate the certificate step by step

```
openssl req -newkey rsa:1024 -out request.pem -keyout client.pem
openssl req -x509 -days 3650 -new -out cert.pem -key client.pem
cat cert.pem >> jabber.pem
cat client.pem >> jabber.pem
```

The result looks better with X509 Version 3

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            f4:fe:a8:c3:a6:f5:be:26
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=AU, ST=Some-State, O=Internet Widgits Pty Ltd
        Validity
            Not Before: Jan 15 16:41:22 2017 GMT
            Not After : Jan 13 16:41:22 2027 GMT
        Subject: C=AU, ST=Some-State, O=Internet Widgits Pty Ltd
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (1024 bit)
                Modulus:
                    00:c0:24:b1:64:bc:ec:38:30:6a:4c:a8:e9:42:22:
                    2c:fa:a7:45:d7:07:01:9c:5b:60:37:5a:ea:6e:6a:
                    78:e1:fa:98:6e:6a:77:9e:35:0a:70:5c:fa:40:67:
                    ec:6b:46:01:2d:72:18:3b:10:bb:5b:68:03:5c:f0:
                    d1:70:48:73:d5:cb:48:4e:ee:8d:d1:86:2e:0d:21:
                    73:c1:44:7e:dc:15:7a:fa:d1:ff:5f:be:77:0b:f5:
                    62:b5:e1:bb:6d:30:c0:35:ef:84:75:14:90:7c:18:
                    ed:53:aa:88:e2:c7:20:8b:c7:b2:5b:29:05:53:ab:
                    4b:9a:d9:eb:7e:34:f9:f3:4b
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Subject Key Identifier: 
                5F:D9:85:48:42:77:57:3E:35:A8:49:79:76:44:63:40:3F:67:8D:99
            X509v3 Authority Key Identifier: 
                keyid:5F:D9:85:48:42:77:57:3E:35:A8:49:79:76:44:63:40:3F:67:8D:99

            X509v3 Basic Constraints: 
                CA:TRUE
    Signature Algorithm: sha256WithRSAEncryption
         0e:98:10:39:97:53:d8:68:85:a5:d3:88:9d:7b:1a:fb:a3:80:
         8b:4c:e0:67:35:37:ca:5c:f9:d9:74:b7:7b:78:c7:71:7e:94:
         5d:68:58:0b:10:72:cd:5b:31:07:f9:25:48:3d:22:8c:34:8e:
         31:1a:ce:8c:a0:97:16:80:7f:35:0e:f0:2e:b5:ad:65:0e:b8:
         ba:0f:21:0c:23:29:a1:e6:af:a5:58:6f:65:c2:37:4f:1a:8f:
         df:c0:00:04:ab:4e:c9:8b:bf:bb:f2:88:21:0b:7c:4a:6b:00:
         83:3d:c6:5e:98:47:d4:af:45:a6:35:e4:c3:21:eb:ab:c6:8a:
         94:f6
```

But again - jabberd is coring trying to load this!

Here are the files:
[Jabber.zip](https://github.com/jabberd2/jabberd2/files/706732/Jabber.zip)

**Comment by lifeofguenter** [comment]
summary of the current state of enabling letsencrypt with jabberd2: https://developer.pidgin.im/ticket/17148#ticket

bit disappointed :/
