### ISSUE TITLE
Subscribing to mailing list failed

### ISSUE THREAD

**Issue by karstengit** [jabberd2/jabberd2#139]
I tried to follow the instructions:
Mailinglist: jabberd2@lists.xiaoka.com (Subscribe by sending mail to jabberd2-subscribe@lists.xiaoka.com)

I send an email with the subject "subscribe" to jabberd2-subscribe@lists.xiaoka.com and get this answer:

> This message was created automatically by mail delivery software.
> 
> A message that you sent could not be delivered to one or more of its
> recipients. This is a permanent error. The following address(es) failed:
> 
>   jabberd2-subscribe@lists.xiaoka.com
>     SMTP error from remote mail server after RCPT TO:<jabberd2-subscribe@lists.xiaoka.com>:
>     host xkh98.infr.xiaoka.com [78.47.138.98]: 550 unknown recipient
>

**Comment by smokku** [comment]
This is `jabberd2+subscribe@lists.xiaoka.com` not `jabberd2-subscribe@lists.xiaoka.com`

**Comment by karstengit** [comment]
O.K. Why i can find then "jabberd2-subscribe@lists.xiaoka.com" at https://github.com/jabberd2/jabberd2 ?

Please update the documentation.

**Comment by karstengit** [comment]
It seems to be the same with the "+" address.

I checked the mail logs and find:
`2017-01-15 12:08:41 H=xkh98.infr.xiaoka.com [78.47.138.98] sender verify defer for <jabberd2+bounces-confsub-5ba6708475223b4b-forum=decotrain.de@lists.xiaoka.com>: Could not complete sender verify callout`
