### ISSUE TITLE
c2s/s2s/sm: connection attempt to router failed: Bad address (14)

### ISSUE THREAD

**Issue by minfrin** [jabberd2/jabberd2#176]
When c2s, s2s and sm attempt to connect to the router, the connections fail as follows:

    Mar 23 17:03:52 server jabberd/sm[25744]: attempting connection to router at server.example.com, port=5347
    Mar 23 17:03:52 server jabberd/sm[25744]: connection attempt to router failed: Bad address (14)

Posix error 14 is as follows:

     [EFAULT]           The address parameter specifies an area outside the process address space.

Which implies something that would otherwise trigger a segfault.

Has anyone encountered this before?

This is jabberd v2.6.1 as deployed via RPM from EPEL on CentOS7.

**Comment by minfrin** [comment]
Looks like on these two lines of code:

https://github.com/jabberd2/jabberd2/blob/0a0fe40ab12dd47f402bb3fed742748189a50c00/mio/mio_impl.h#L404

https://github.com/jabberd2/jabberd2/blob/0a0fe40ab12dd47f402bb3fed742748189a50c00/mio/mio_impl.h#L417

the EFAULT error code is being misused to mean that something could not be recognised as an IP address, instead of the real meaning, which is that the memory address is invalid and would otherwise trigger a segfault.

This needs to be fixed to avoid a wild goose chase.

**Comment by YmrDtnJu** [comment]
I think, you need to specify the IP address of the router and not its hostname.
