### ISSUE TITLE
mysql: connection to database failed

### ISSUE THREAD

**Issue by hasufell** [jabberd2/jabberd2#180]
```sh
# sudo -u jabber -g jabber /usr/bin/sm -D -c /etc/jab
ber/sm.xml
Thu Jun  7 02:45:44 2018 [notice] starting up
Thu Jun  7 02:45:44 2018 [info] process id is 7806, written to /var/run/jabber/jabberd2-sm.pid
Thu Jun  7 02:45:44 2018 storage.c:96 adding arbitrary types to driver 'mysql'
Thu Jun  7 02:45:44 2018 storage.c:119 driver not loaded, trying to init
Thu Jun  7 02:45:44 2018 [info] loading 'mysql' storage module
Thu Jun  7 02:45:44 2018 storage.c:141 preloaded module 'mysql' (not initialized yet)
Thu Jun  7 02:45:44 2018 storage.c:161 calling driver initializer
Thu Jun  7 02:45:44 2018 [error] mysql: connection to database failed: Can't connect to MySQL server on 'jabberd2-mysql.jabberd2' (111)
Thu Jun  7 02:45:44 2018 [notice] initialisation of storage driver 'mysql' failed
Thu Jun  7 02:45:44 2018 [error] failed to initialise one or more storage drivers, aborting
```

connecting via `mysql -u jabberd2 -h jabberd2-mysql.jabberd2 -p` works perfectly. Mysql is up and running and doesn't give any useful errors/info.

mysql version is 5.7.22, jabberd 2.6.1, mysql support is compiled in

**Comment by YmrDtnJu** [comment]
I am not really familiar with the notation "jabberd2-mysql.jabberd2". I guess, you don't have an internal TLD named jabberd2, so it must be the database's name. Is that correct? In this case, I think, that maybe only the mysql client application supports that notation.

Would you please either post the parts of sm.xml that configure your database connection or take a look at "Set storage module to use in sm.xml" at the [Quick Start Guide](https://github.com/jabberd2/jabberd2/wiki/Installguide-quickstartguiderpm)

**Comment by hasufell** [comment]
> I am not really familiar with the notation "jabberd2-mysql.jabberd2". I guess, you don't have an internal TLD named jabberd2, so it must be the database's name.

That is the docker network and it's perfectly fine and has worked before.

I think it must have been data corruption. But since I have switched to ejabberd, I don't really care anymore and this can be closed.
