### ISSUE TITLE
s2s cannot connect to ipv6 servers, "Address family not supported by protocol"

### ISSUE THREAD

**Issue by crosser** [jabberd2/jabberd2#30]
On the kernels newer than about 3.0, connecting to other hosts that have ipv6 address does not work. This is because the server tries to bind a socket to "source IP" which is at least in my case ipv4, but the socket was created in the address family of the destination IP address. New Linux kernels forbid this.

See also my comment on a commit in mio/mio_impl.h

**Comment by smokku** [comment]
Should be fixed in 2.4.0.
Closing. Feel free to reopen if this still fails.
