### ISSUE TITLE
maximum allowed optimization level is -O2

### ISSUE THREAD

**Issue by ryandesign** [jabberd2/jabberd2#34]
Configuring jabberd 2.2.17 with `-Os` in `CFLAGS` fails with:

```
checking CFLAGS optimization level... configure: error: maximum allowed optimization level is -O2
```

Why?

This was check was added to the configure script in 618c20417c6a08eda71d931ec34365706ef4961e 6 years ago. Is it really still a problem today?

The commit message says it fixed "#100" but there are not that many issues in this issue tracker so I presume it refers to an older issue tracker.

[FreeBSD removes this check](http://ftp.netbsd.org/pub/pkgsrc/current/pkgsrc/chat/jabberd2/patches/patch-configure) and I am considering doing so for MacPorts as well, since MacPorts 2.2's default optimization flags are `-Os`.

**Comment by hasufell** [comment]
I don't have any problems with recent gcc-4.8.5 and clang-3.7.0, so I'd vote for removing this check.
