### ISSUE TITLE
File transfers

### ISSUE THREAD

**Issue by medikoo** [jabberd2/jabberd2#38]
Sorry, I'm not that familiar with internals, and I can't find any information on that.

Do jabberd2 provides file transfers out of a box? If it's so, is there any documentation how it should be configured?

If it doesn't, are there any known working "pugins" that bring that functionality?

Thanks!

**Comment by hasufell** [comment]
sorry for necro, but there is also [XEP-0363](https://xmpp.org/extensions/xep-0363.html) which could be considered... however, should definitely be optional since it's privacy-invasive to store potentially private files on a foreign server

**Comment by crosser** [comment]
I have XEP-0363 service running in conjunction with unmodified jabberd2 via python [HttpUploadComponent](https://github.com/siacs/HttpUploadComponent) which is somewhat fragile but works.

**Comment by hasufell** [comment]
Can this be reopened and renamed to __XEP-0363: HTTP File Upload__?
