### ISSUE TITLE
service doesn't autostart

### ISSUE THREAD

**Issue by thany** [jabberd2/jabberd2#64]
Every single time my server reboots I have to login and do

```
sudo service jabberd2 start
```

All the other services that I installed register themselves properly to autostart with the system, except for jabberd2. I just installed it via apt-get, and made the proper configuration. How can I make it autostart? It'll be the last obstacle until it's running absolutely smooth.

I did notice there's a jabberd2 script in `/etc/init.d` but I don't know how to make that into an autostart thing, since I've never had to do such a thing (and IMO shouldn't be neccesary).

So, bug? Or should autostart just work and have I missed something?...

Running Ubuntu 14.04 LTS, jabberd2 2.2.17 (latest from apt-get as of the time of writing).

**Comment by vflyson** [comment]
Here's a modified script for OpenRC taken from Gentoo, works for me on Alpine Linux https://gist.github.com/vflyson/3083faa9ebb415327b08a404c15f2506
