### ISSUE TITLE
Create a self-signed cert for TLS usage on installation

### ISSUE THREAD

**Issue by tfar** [jabberd2/jabberd2#92]
It would be nice if jabberd2 shipped with a default config, that had TLS enabled for C2S and S2S connections. All that needs to be done for this is to generate a self-signed certificate for this on installation and set this in the default config for jabberd2 to use in https://github.com/jabberd2/jabberd2/blob/master/etc/s2s.xml.dist.in . This way default installations of jabberd2 would support opportunistic encryption, and raising the attack barrier to active attacks.

**Comment by smokku** [comment]
Shouldn't we leave this decision to distributors?

**Comment by Flowdalic** [comment]
From my experience, distributions are happy if they don't have to apply custom configuration cause it is causing extra work when packaging. Shipping jabberd2 with opportunistic encryption enabled by default appears to be a good idea. And if someone (a distro) disagrees then they can apply custom configuration.

**Comment by smokku** [comment]
I see two issues with this approach:
  - certificate gets generated on machine jabberd2 is built, not a machine it gets installed, leading to wrong hostname and/or every instance of jabberd2 having same certificate
  - self-signed certificate is really a false sense of security. Yes, one cannot trivially sniff unencrypted traffic, but mounting a man-in-the-middle attack is close to trivial with self-signed certs
