### ISSUE TITLE
Sign releases

### ISSUE THREAD

**Issue by jas4711** [jabberd2/jabberd2#93]
As we are packaging jabberd2 for Debian, one of the automated checks that we ran into is that upstream releases should be cryptographically signed.  Would you consider signing releases using OpenPGP and upload the *.sig file?  Thanks!

**Comment by smokku** [comment]
Sure.
Signatures added to the release.

**Comment by jas4711** [comment]
Thank you!

Would you mind also signing the "Source code" zip/tarball?  That is the actual source we use for the Debian package.  The reason for that probably warrants a separate issue, I'll open that...

**Comment by smokku** [comment]
Nope.
I won't be signing stuff not generated by me.

**Comment by jas4711** [comment]
I didn't realize those files weren't generated by you.  Makes sense.

**Comment by smokku** [comment]
These are tarballs auto-generated by github for every release-tag.
As such they are not really directly usable to build jabberd, because repository source does not contain autotools files - just templates. I am doing standard "make dist" to create release tarballs, as described in tools/git file.
