### ISSUE TITLE
No source for obfuscated docs/code/jquery.js in releases

### ISSUE THREAD

**Issue by jas4711** [jabberd2/jabberd2#94]
The docs/code/jquery.js file is obfuscated, but no source appears to be available in the release tarball.  One of the automated Debian checks caught this.  I don't know what the recommended way to solve this is, but generally I can think of two ways: 1) Ship an non-obfuscated jquery.js (source code form), or 2) Ship source code and build the obfuscated jquery.js.  There may be ways to configure doxygen to not output this file too.

This problem is the reason the Debian package use the "Source code" release tarballs at the moment.  We don't strictly need this problem solved, since using the source code, or get the source from git directly, is possible.  But I thought I'd spell this out, since it came up in #93.

**Comment by smokku** [comment]
docs/code is autogenerated Doxygen documentation. I don't consider it a "source". The source code for this documentation is the source code itself.
It is being distributed in a release tarball as a convinience. If you do not like it, you are not required to ship it. Also you may rebuild the documentation yourself using your own version of Doxygen.
