### ISSUE TITLE
s2s: on a host with IPv4 and IPv6, if no <origins>, diagnostic is misleading

### ISSUE THREAD

**Issue by crosser** [jabberd2/jabberd2#96]
On a host with IPv4 and IPv6 address, if there is no &lt;origins&gt;section, address from &lt;ip&gt; is used as the only element of origin_ips array. If the remote host has only address in the other family, mio_connect is never used in the loop at out.c:583, and (*out)->fd == NULL) at the exit from the loop. Connection to the host is not established, and because no attempt to connect was made, errno has some irrelevant value (in my case, it was 11 "Resource temporarily unavailable"). As a result, log_write at out.c:548 produces misleading message, like:

Apr 27 23:58:36 dehost jabberd/s2s[19087]: [-1] [173.194.72.125, port=5269] mio_connect error: Resource temporarily unavailable (11)

If no suitable origin_ip was found, default should be used. Or, at the very least, the diagnostic should say that "suitable origin IP was not found for the destination IP xxxx".

**Comment by brianjmurrell** [comment]
This issue was opened quite a while ago now without even a single comment or triage one way or another.  Will this issue be fixed any time soon?  Is there any known usable workaround?

If not, any suggestions for an xmpp server than can be used with both IPv4 and IPv6?

**Comment by crosser** [comment]
The workaround is to create the <origins> section and put both ipv4 and ipv6 addresses there:

    <origins>
      <ip>xxx.xxx.xxx.xxx</ip>
      <ip>2xxx:xxxx:xxxx:xxxx::x</ip>
    </origins>

**Comment by brianjmurrell** [comment]
On Mon, 2015-11-02 at 01:28 -0800, Eugene Crosser wrote:
> The workaround is to create the <origins> section and put both ipv4
> and ipv6 addresses there:
> 
>     <origins>
>       <ip>xxx.xxx.xxx.xxx</ip>
>       <ip>2xxx:xxxx:xxxx:xxxx::x</ip>
>     </origins>

Indeed.  And I did do this, however now I have a(nother) configuration
file that I have to edit every time I add/delete a network to/from this
machine.  Assuming I can even have more than one origin for a given
class (i.e. multiple IPv6 origins) since I did only add one of mine and
am now limited to making connections on only one of my several IPv6
interfaces.

**Comment by rachelbythebay** [comment]
Try this:

[jabberd.dualstack.patch.txt](https://github.com/jabberd2/jabberd2/files/233114/jabberd.dualstack.patch.txt)

Assuming you have &lt;ip>::&lt;/ip> in your <local> part of s2s.xml, this should work on 2.3.6.

And yeah, it's goofy as hell.  It's just doing what 2.2.14 used to do, which is to use local_ip as origin_ip.

**Comment by smokku** [comment]
@rachelbythebay Will connecting IPv4 host work with `::` specified as origin_ip?

**Comment by smokku** [comment]
Answering my own question: As mentioned in #30 connecting IPv4 address using IPv6 source address will not work. But answering such connection works.
So, the following configuration works for multihomed/multiprotocol boxes:
```xml
  <local>
    <ip>::</ip>
    <port>5269</port>
    <origins>
      <ip>::</ip>
      <ip>0.0.0.0</ip>
    </origins>
```

**Comment by minfrin** [comment]
Did the original bug "diagnostic is misleading" get fixed?

I am getting a similar bizarre error message, where a failure to listen returns "No such file or directory" on a CentOS7 machine.

jabberd/router[24901]: [server.example.com, port=5347] unable to listen (No such file or directory)

(This time the ID resolves to both an IPv4 and IPv6 address, and I want it to bind to one interface, not all interfaces)

**Comment by smokku** [comment]
Unfortunately this is a (mis)feature of Unix, that ENOENT gets "translated" to _No such file or directory_ by strerror() function.
https://stackoverflow.com/questions/19902828/why-does-enoent-mean-no-such-file-or-directory

Getting it special handled is generally not worth the hassle. Any seasoned Unix administrator had learned the lesson that _No such file or directory_ really means that _Accessed resource (maybe a file) is missing_.

**Comment by crosser** [comment]
The problem that I originally reported is not about (mis)interpretation of ENOENT, but about `errno` being used in the message "uninitialized", when it carries a result of some long forgotten operation, rather than the reason of the latest failure.
