### ISSUE TITLE
XEP-0065 & BSD kqueue

### ISSUE THREAD

**Issue by brahmann** [jabberd2/jabberd2#97]
Hi jabberd2 dev team, thank you for your work.
Can you add base support of XEP-0065(and related XEPs) for server-side file proxy ?

And can you add kqueue support when compiling on BSD systems?
From FreeBSD ports jabberd2 uses select as i see. 

Thank you for any answer.

**Comment by smokku** [comment]
kqueue support is already present: https://github.com/jabberd2/jabberd2/blob/master/mio/mio_kqueue.h

**Comment by brahmann** [comment]
how to enable it when installing from freebsd ports? 
 1162 jabber        1  20    0 47292K  9068K select  0   0:55   0.00% s2s
 1161 jabber        1  20    0   108M  9652K select  0   0:39   0.00% sm
all components use select or i miss something?

**Comment by smokku** [comment]
Unfortunately I know nothing about freebsd ports.

**Comment by brahmann** [comment]
so this an issue, okay i will ask port maintainer, thank you for your answers

**Comment by brahmann** [comment]
Okay, port holder did update to port, and this issue fixed on BSD, now jabberd2 on freebsd installed from ports using kqueue - confirmed. So only feature request here for XEP-0065 and related XEPs for server build-in file proxy service :+1: 

52958 jabber        1  20    0 60460K 10964K kqread  0   0:00   0.00% c2s
52957 jabber        1  20    0 43032K 10576K kqread  0   0:00   0.00% s2s
52956 jabber        1  20    0   103M  8540K kqread  1   0:00   0.00% sm
52955 jabber        1  20    0 38900K  5396K kqread  1   0:00   0.00% route
